[package]
name = "tiptoe-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.3.3"
candle-nn = "0.3.3"
candle-transformers = "0.3.3"
tokenizers = "0.15"
hf-hub = "0.3.2"
anyhow = "1.0"
serde_json = "1.0.134"
simplepir = "1.0.1"

[dev-dependencies]
approx = "0.5.1"

[profile.dev]
overflow-checks = false